public class Class3 {
    public static void method3(){
        List<integer> Highnumber = New List<integer>();
        integer a = 20;
        integer b = 30;
        integer c = 30;
        
        if(a==b){
            system.debug('a is greater');
            
        }
            else if(b==c){
                system.debug('b is greater');
            }
            
            else{
                system.debug('c is greater');
            }
            
        }
        
    }