public class Class7 {
    public static void method7(){
        map<integer,string> Namenumber = new map<integer,string>();
        Namenumber.put(1,'anil');
        Namenumber.put(2,'anil');
        Namenumber.put(3,'pavan');
        Namenumber.put(4,'kumar');
         Namenumber.size();
        system.debug('print name and number;;;'+Namenumber);
        
       
            
            
            }
    
}