public class StudentMap {
    public static void studentNoNameMap()
    {
    Map<integer,String> studentNoNameMap = new Map<integer,string>();
    
    studentNoNameMap.put(1,'anil');
    studentNoNameMap.put(2,'pavan');
    studentNoNameMap.put(3,'praneeth');
    studentNoNameMap.put(4,'naveen');
    
    system.debug('Map;;;'+studentnoNameMap); 
    
    system.debug('...value at 1 key;'+studentnoNameMap.get(1));  
    
    system.debug('Size;;;'+studentnoNameMap.Size()); 
        
}
}